### ISSUE TITLE
Authentication error not shown to user, causes changes to be lost.

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#100]
Users not always prompted to login. They can continue to use the App and make changes but none of the changes are saved to the server.

Consider using a error message that does not disappear, similar to gmail's network error message: 
![image](https://user-images.githubusercontent.com/10155226/83836322-41ea8480-a71d-11ea-8f11-b3af3ad8b606.png)

**Comment by jamesduncan** [comment]
I have put in place two prompts now. One that notifies you when you are offline and another when you cannot communicate with the server (vpn issues, server is rebooting or server is down)
