### ISSUE TITLE
Switching between Data Collections not working

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#104]
Bug found at Accounting App/ *Data Collections/ [Dashboard Fiscal period, Dashboard lBalance, Dashboard aBalance ]

User selects Data Collection A
Changes the the data source for A, thaa change is applied to Data Collection A.

User then selects Data Collection B
Changes the data source for B, that change is applied to Data Collection **A AND B**.

Difficult to reproduce? This doesn't seem to apply for Data Collection C.
It may only be data sources?

**Comment by wongpratan** [comment]
@Achoobert 
It should be fixed and in the trial site.
Please test and confirm it pass.
