### ISSUE TITLE
PM Query Task unable to find process object

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#105]
Process Manager Query Task unable to find process object

**Reproduce:**
1. Create a process with an object lifecycle trigger
2. Configure the trigger selecting any object
3. Add a new service task > query task.
4. Select the object used in the trigger
5. Select 'find'

**Console error:**
![image](https://user-images.githubusercontent.com/10155226/85259276-f7923300-b492-11ea-92b3-14180188cada.png)

**Comment by Hiro-Nakamura** [comment]
We need to run this by Pong to see what the current method for adding unique filter conditions to the FilterComplex widget is now.

**Comment by jamesduncan** [comment]
Okay we have a fix for this but we need to make some changes to the fields settings when this goes live. I can work on pushing it live tomorrow on both Trial and Demo.
