### ISSUE TITLE
Scope management popup

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#106]
Allow user to resize window?

![image](https://user-images.githubusercontent.com/8057443/85370020-4c4bb180-b558-11ea-8d18-fb195af7cc48.png)

display full information on furthest left dropdowns

![image](https://user-images.githubusercontent.com/8057443/85370126-7309e800-b558-11ea-87c7-c1cd7adeb178.png)

**Comment by jamesduncan** [comment]
The modal is resizable now.
