### ISSUE TITLE
We need to come up with a solution that does not load all connected records into a field to speed up queries

### ISSUE THREAD

**Issue by jamesduncan** [appdevdesigns/app_builder#109]
<img width="1608" alt="Screen Shot 2020-07-01 at 10 46 16 AM" src="https://user-images.githubusercontent.com/106924/86200970-59842400-bb88-11ea-9fcb-6679d5439403.png">

For connected fields that are going to be connected to may records this is going to be more of a problem going forward. You cannot simply hide the field because we still load all fields and connected records.

**Comment by nh758** [comment]
Next step #138
