### ISSUE TITLE
Credit/Debit are not calculating decimal places 

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#113]
To Replicate:
1. In an Unsubmitted Batch, enter decimals in credit and debit fields, i.e. Credit Total = 20.12, Debit Total = 20.51
2. Click SAVE AND SUBMIT BATCH button, no "Your batch must be balanced" window pops up. and the batch goes to Submitted Batches page.

**Comment by jamesduncan** [comment]
This should be fixed now...can you test and resolve Wei?

**Comment by wei9528** [comment]
Verified, it is fixed.
