### ISSUE TITLE
Unable to import CSV data containing Chinese characters

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#114]
1. Add some Chinese characters in a JEs CSV file, i.e. 中国字
2. Go to a unsubmitted batch, Import the CSV file
You will see these unreadable words as below screenshot shown  
![CSV](https://user-images.githubusercontent.com/67583075/86584778-05c67000-bfb8-11ea-92b6-1565469c877e.png)

**Comment by nh758** [comment]
@wei9528 please test and confirm that this is fixed now

**Comment by wei9528** [comment]
To import Chinese characters, make sure the .CSV file Save As CSV UTF-8 (Comma delimited).csv type.
