### ISSUE TITLE
[Menu widget] Menu button text un-translating itself

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#116]
This button is translated
![image](https://user-images.githubusercontent.com/8057443/86893823-68d91380-c12c-11ea-9837-5df44e5b484d.png)
The page it links to is translated into thai, but the menu selection for getting it does not update
![image](https://user-images.githubusercontent.com/8057443/86893964-9625c180-c12c-11ea-90d0-45d4c7193eae.png)

**Comment by jamesduncan** [comment]
#129 This pull request should fix menu issues.
