### ISSUE TITLE
CSV Import all records incorrectly failing validation

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#118]
Error shows problem with Debit or Credit, though Debits and Credits in the CSV should pass validation (Trial Site)
![image](https://user-images.githubusercontent.com/10155226/86999212-430b4780-c1dc-11ea-9d5f-de559b157a27.png)

**Comment by wei9528** [comment]
Pong has been looking into it.

**Comment by wei9528** [comment]
There will be another issue if adding credit=debit validation during import, if JEs records > 1000, these records have to be divided into smaller ones, then it is hard to make sure credit = debit.
