### ISSUE TITLE
edit [🖊] in connected field linking to wrong form and popup

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#119]
>on both Trial and live CARs site

On the CARS app/ Edit Child's Information/Social Work/ Notes / (+ add Note)
when adding a new file record via the connected field [+] button, it will reset the cursor to an existing note record -- this erases any work on the un-saved note record.

To reproduce,
Select any **child**, goto **social work/notes,** "Add note" menu button

![image](https://user-images.githubusercontent.com/8057443/87118004-5c77c680-c2a4-11ea-84bf-460908ead184.png)

**Comment by jamesduncan** [comment]
@Achoobert can you verify this is working correctly? I think a possible bug could still be present in that the popup doesn't automatically close when you click save...I can look at that next.

**Comment by Achoobert** [comment]
![image](https://user-images.githubusercontent.com/8057443/98786407-a4645100-2430-11eb-879c-6e8283411ba5.png)
-still getting submit rules redirection
-popup not closing
-data not saving OR not showing the change when you re-open the form?????

**Comment by jamesduncan** [comment]
Okay popup closes now....save should be more reliable as well.

**Comment by Achoobert** [comment]
Looks like it's working!
