### ISSUE TITLE
GL Transactions Report content is blank on VPS server 

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#125]
To Replicate:
1. Log into VPS server, https://vps-internal.appdevdesigns.net/
2. Go to Reports > GL Transactions, select FY20 M11, click GL Transactions Report (one month)
Open the downloaded .doc report, which only has title GL Transactions for FY21 M03.

**Comment by nh758** [comment]
Found one issue was the cursor was set to FY21 M03. Changed to Default first record.
![image](https://user-images.githubusercontent.com/10155226/88006818-c27f0c00-cb36-11ea-8b88-e383e0e65eee.png)
However still not seeing expected transactions. My guess is some of the other data collections may have missing connections or selections,

**Comment by wei9528** [comment]
Fixed, report shows correctly now. Closing.
