### ISSUE TITLE
Add Sorting in GL Report

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#128]
Now the order of GL reports is random.(or I did not figure out how it sorts)  
Please sort the report based on COA and RC in ascending order. 
This is an example of GL Report from FCX, 
![Screenshot 2020-07-24 at 10 37 02 AM](https://user-images.githubusercontent.com/67583075/88356236-bc3c9a00-cd99-11ea-9ef4-0e5fde540c26.png)

**Comment by wongpratan** [comment]
I added the sort ability to 1:M connect field.
