### ISSUE TITLE
Submit rule not redirecting to sub-tab

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#137]
submit rule not redirecting to sub-tab
Is instead sending user to 'home' (top page where the tab widget is)

This bug has been fixed for menu already :) 

![image](https://user-images.githubusercontent.com/8057443/90094516-591aa380-dd58-11ea-9a60-9a6122a61f9c.png)

**Comment by jamesduncan** [comment]
I switched it to go to Reports and it worked fine...there seems to be something about the Transactions page that it doesnt like...looking closer now.

**Comment by jamesduncan** [comment]
This has been fixed and tested on VPS.
