### ISSUE TITLE
Pivot table not showing columns when data collection is linked

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#139]
Location: VPS-internal / accounting app / home / Responsibility Center / View RC

Test: there are two pivot tables in this location. Both are using queries. One of them is, on the data collection, linked to an RC collection. 

![image](https://user-images.githubusercontent.com/8057443/90369339-d1090680-e095-11ea-9744-686eabf07983.png)

This breaks the pivot table widget thusly.
![image](https://user-images.githubusercontent.com/8057443/90369505-175e6580-e096-11ea-97da-0f50f706b417.png)

**Comment by nh758** [comment]
I reproduced the problem, it's more specific: When the data collection is based on a query and linked to another data collection the pivot table shows no field options. Data collections not based on a query still work when linked.
