### ISSUE TITLE
Phantom fields appear in Grid (cannot be hidden)

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#148]
**Describe the bug**
Fields in Grids displayed that cannot be hidden/do not appear in appbuilder.

The Setup > RC Grid shows an extra field 'Personal RC'. This field does not appear anywhere in App Builder, no option to hide it.

**Server**
Trial (Accounting App)

**Screenshots**
![image](https://user-images.githubusercontent.com/10155226/91544683-41434200-e94a-11ea-9411-b4236617c9f4.png)
![image](https://user-images.githubusercontent.com/10155226/91544770-659f1e80-e94a-11ea-893c-b8e0ca3e6e1c.png)

**Additional context**
Also an extra un-labeled field showing on the projects grid.
![image](https://user-images.githubusercontent.com/10155226/91544991-b4e54f00-e94a-11ea-8f9c-55d78b918030.png)

**Comment by jamesduncan** [comment]
Okay we found out that "Personal RC" is a connected field in the "Stewardwise 2" application. The additional field does not show on the "Preview" mode of Interface Builder. It only shows when you are viewing the live app. I am not sure what we are doing differently to filter the fields on the "Preview" mode that we are not doing on the "Live" view but I think we probably want fields that are not present in the current app to be hidden. Right now we can import the "Person" field from the "Stewardwise 2" app then hide the "Personal RC" field in the "Responsibility Center" app as a work around, but it would be good to hear from @Hiro-Nakamura and @wongpratan on what they think it should do by default.

**Comment by jamesduncan** [comment]
On another note I think because of these phantom fields the last column on data grids is not properly sized because we are counting these fields in the total number of fields available and it is hard to know which field is actually the last one to autosize its column. Not critical...just noticed it.

**Comment by Hiro-Nakamura** [comment]
@wongpratan 
This particular example field is a mis-configured connect Field in the db.  Specifically `object[Responsibility Center]->field[Personal RC]`  is trying to point to `object[Person]->field[06d83bed-4a3e-4218-98dc-dfb9a2bdc870]`  but `Person` doesn't have a `field[06d83bed-4a3e-4218-98dc-dfb9a2bdc870]`

There are a number of other instances of this in the Arango Definitions.

**Comment by jamesduncan** [comment]
It looks like this is working on Experimental...I am guessing it was fixed or another fix took care of it.
