### ISSUE TITLE
Page permissions broken

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#150]
**Describe the bug**
page permissions broken in a specific app

**To Reproduce**
1. Go to 'leave tracking'
2. See error
-error pops at upper right
-in console

I believe this is caused by
1. create role
2. assign role 'page permissions' in an app
3. Delete role
4. app now cannot load page permissions

**Expected behavior**
Page manager button/popup to show

**Server**
 Trial

**Screenshots**

![image](https://user-images.githubusercontent.com/8057443/92345993-9e32bb00-f0f5-11ea-8f41-5f6ed3d91690.png)

**Comment by nh758** [comment]
Have you tried adding another role to resolve it? In general we want to assign at least the builder role (Full Access) as the AP Manager so they can see the App their building.

**Comment by jamesduncan** [comment]
Can you test this on trial now and see if it works as you would expect?

**Comment by Achoobert** [comment]
@jamesduncan LGTM! The fix works
