### ISSUE TITLE
[Accounting App][Change Request] COA dropdown list dependent on the option selected in RC dropdown list

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#157]
This is a change request from NS. They would like to set conditions between COA and RC dropdown lists, so if the app can do the data validation, they do not have to check that COA and RC pairs are matched.
Here are two examples. 
If user select **Q000-NSTR** or **Q000-KBNK** in the RC dropdown list, the COA dropdown list can only populate value **1231**
If RC contains **SOWE**, the corresponding COA must be **1233**

**Comment by nh758** [comment]
@wei9528: I have some questions, trying to figure out what it would take
1. Is this just for the add JE form, or is it requested for the CSV uploader tool as well? 
2. The pairs will be for all accounts and rc or just certain ones?
3. Who will add/maintain these pairings?
4. How high of a priority is this?

**Comment by wei9528** [comment]
@nh758 Good questions. 
1. The data validation should also add in CSV uploader, but if the cost is too high, and since they will not use "CSV" to load data after the SW 2.0 app is done, to add the validation in CSV uploader is low priority.
2. Now the pairs are just the two examples I listed above. 
3. All accountants who add JEs will add that, and Finance Leader will check out that. 
4. Not 'must have' feature, but if have, will avoid some mistakes, and save some time for FL to check out those pairings.

**Comment by nh758** [comment]
@Achoobert do you know of way to add this to the form or would this require changes to the platform? I'm pretty sure the CSV uploader would require changes.

**Comment by Achoobert** [comment]
If you're thinking of this "add draft entry" popup, **no**. There is currently no way of making inter-form dropdowns be inter-dependent.
![image](https://user-images.githubusercontent.com/8057443/93291170-91584a80-f80c-11ea-9def-2a8e553f9d7c.png)

It is possible to filter "X" based on user selection of "Y," but it has to be in a different form or different widget.
'select from list of X' =[new page, or different widget]=> 'select from list of Y'

So
Putting a grid above this form with the 'accounts' in it, then we could filter the 'RC's in the form based on the users selection

This would look awkward and only be one-way (you wouldn't be able to filter 'accounts' based on which 'RC' is selected)

**Comment by nh758** [comment]
added appdevdesigns/planning#64
