### ISSUE TITLE
[AppBuilder] Bulk Update is not working correctly

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#158]
Testing environment: VPS
To Replicate:
Go to an object builder, or go to Accounting app, Journal Entry grid page. 
Select multiple records, click Edit button, update a field value, notice the values are changing but not updated to the new value, still the old values.
![Screenshot 2020-09-15 at 11 11 53 AM](https://user-images.githubusercontent.com/67583075/93161061-54c11c00-f744-11ea-8fda-6c65f2e494c7.png)

**Comment by nh758** [comment]
I can't reproduce this on Trial. Are you seeing this on VPS?

**Comment by wei9528** [comment]
> I can't reproduce this on Trial. Are you seeing this on VPS?

Yes, on VPS. Trial site is working well.
