### ISSUE TITLE
Restricted scope used when a user has multiple scopes assigned

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#160]
**Describe the bug**
When a user has multiple scopes the more restricted scope is used.

**To Reproduce**
1. Check an Object with multiple records
1. Assign a role with only 'allow all' scope
2. Assign a **separate** role with a scope with a filter on the Object (so that only some of the records pass)
3. Reload the AppBuilder and check the Object
4. Only records that pass the filter in scope 2 are shown

**Expected behavior**
The user should see all records in the Object since they have been given an 'allow all' scope

**Server**
VPS, reproduced on Trial

**Additional Context**
Scopes in AppBuilder > Administration

**Comment by wei9528** [comment]
@wongpratan did you update the VPS server?

**Comment by wei9528** [comment]
Verified on the VPS, when a user is assigned to one of more roles, the user will have the sum of all the permissions for each role the user has. For example if user A is assigned to both Accountant and Finance Leader, Finance Leader's scope is 'allow all', but Accountant's scope is limited, the user can see all records and pages the Finance Leader has.
