### ISSUE TITLE
Extra connected fields in grid widget

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#168]
**Describe the bug**
Can see connected fields in grid widget to objects not in app, so I cannot hide them in grid settings

**To Reproduce**
1. Go to 'trial/profile/profile/baisc info'
2. See grid with too many fields

**Expected behavior**
I expected all fields except basic 'name/birth/gender' to be hidden
However connected fields to objects outside the scope of the app are shown in the grid

**Server**
Trial

**Screenshots**
![image](https://user-images.githubusercontent.com/8057443/93558130-f182f400-f9a6-11ea-8013-b05b61f65978.png)
![image](https://user-images.githubusercontent.com/8057443/93558164-03fd2d80-f9a7-11ea-9c9d-2b03ad754951.png)

**Comment by nh758** [comment]
I think this is the same as #148
