### ISSUE TITLE
[Accounting App] data displays in two users' windows simultaneously

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#171]
**Describe the bug**
When user A is adding journal entries, either through UI or CSV importer, if other users open the journal entries page, they can also see the data importing from user A. 

**To Reproduce**
1. Open https://vps-internal.appdevdesigns.net/ in two browsers, and log in with two users, i.e. User A in Chrome, User B in Safari. 
2. Create two batches. 
3. Open batch A in chrome, open batch B in safari, stay at Journal Entry grid page.
4. Add entry in batch A, notice that that entry adding in batch A is also being added into batch B.  
5. Reload the app, the entry in batch B will disappear.
This issue also exists when importing data through CSV importer.  
![image](https://user-images.githubusercontent.com/10155226/93579967-5d765400-f9c9-11ea-9ace-473d454f45a6.png)

**Expected behavior**
User B should not see that JE added by user A.

**Comment by wei9528** [comment]
Comment by James, "i_t is a problem with our socket updates allowing the entry to show in a data table that has a cursor set that should exclude the entry from showing but instead we look at the data collection without the cursor being set and determine it should be in the data set and pop it in…now I will add the additional step of checking if the table has a cursor set to limit data first before we insert it into the view._

**Comment by jamesduncan** [comment]
Fixed in submodule
