### ISSUE TITLE
[Accounting App][Performance] Failed to close month when dataset is too big

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#172]
**Testing environment**
VPS server
**Describe the bug**
Closing over 5000 JEs, the Status of fiscal month cannot be updated to Closed. It always displays “Closing”. the data is getting doubled and tripled, because I guess we clicked the “Close Month” button two or three times,
**To Reproduce**
Prerequisites: Journal Entries of "Completed Batches" in current month should be big enough, >5k?
1. Make sure current month's JEs are all in "Completed Batches". 
2. Go to Setup > Fiscal Periods, click Close Month button on the Fiscal Periods page.  
3. Click Close Month button on the popup window.
4. Notice the Status of that month closed on #3, still shows Closing after a long time.  
![Screenshot 2020-09-19 at 5 47 42 PM](https://user-images.githubusercontent.com/67583075/93727578-46fd1200-fbee-11ea-84bd-39e446ba8ba7.png)

**Expected behavior**

1. Status becomes "Closed" after ? minutes. 
2. Starting balance equal to previous month ending balance
3. Set next month status "Active"

**Comment by wei9528** [comment]
Users are still waiting for generating the payroll of August, this bug is blocking getting the correct accounts balances, set the priority too high.

**Comment by nh758** [comment]
The amount of Journal Entries or Batches does not effect the process. The close month process only uses balances. It could be the number of balances. We will likely need @wongpratan help to see what's happening. If you can get the process logs that might give us some insights into what went wrong.

**Comment by wei9528** [comment]
Yes, I mean JE in Balances. 
Here is the log I can see, no specific message. 
![Screenshot 2020-09-21 at 12 02 56 PM](https://user-images.githubusercontent.com/67583075/93732199-d7455200-fc02-11ea-8f40-bd64b58a032d.png)

**Comment by nh758** [comment]
Ok thanks, would expect there to be errors... We'll need Pong to look at this tomorrow.

**Comment by wei9528** [comment]
Reset the priority to low, because this performance issue is caused by slow internet speed. 
Retested in another environment, closing month is successfully done.

**Comment by nh758** [comment]
Internet speeds should not be a factor for this. The process is run server side, so as long as the process trigger is received by the server, the process should complete. We will need to look at this more to understand the problem.

**Comment by wei9528** [comment]
"Process Manager" really goes very slow when the Internet/VPN connection is very slow. and my VPN speed is slow when the speed of the Internet is low...

**Comment by wei9528** [comment]
This is an occasional bug occurred in a poor network connection. 
Close, we can reopen it if it is stable to reproduce.
