### ISSUE TITLE
[App Builder Enhancement] Combining the AND and OR conditions in a query

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#174]
Now you can only use AND **or** OR operator to filter records, when you change one condition to AND, all conditions will become AND. Enhance to use the AND **and** OR operators to combine two or more conditions into a compound condition.
![Screenshot 2020-09-21 at 1 30 45 PM](https://user-images.githubusercontent.com/67583075/93735354-3c9f4000-fc0f-11ea-9032-811f337fa7e9.png)

**Comment by nh758** [comment]
Could move to webix's [query builder](https://docs.webix.com/desktop__query_builder.html), thought they will not continue to develop it. 
Their complex widget [query](https://webix.com/widget/querybuilder/) is an option but will require an extra license.

**Comment by nh758** [comment]
Added appdevdesigns/planning#25
