### ISSUE TITLE
Error adding Connected Records

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#180]
**Describe the bug**
When adding a Connected Record an error is displayed.

**To Reproduce**
Does not happen each time, but have seen the error multiple times.
1. When adding a Connected Record an Error Message is displayed
2. On reloading the field shows but no records can be selected.
3. Recreating the connection seems to work.

**Expected behavior**
A connected record field is added without error

**Server**
Experimental

**Screenshots**
![image](https://user-images.githubusercontent.com/10155226/93852508-565a8900-fcdc-11ea-9d9c-775c9131d3f9.png) 
![image](https://user-images.githubusercontent.com/10155226/93852524-5eb2c400-fcdc-11ea-8784-0eef0de0e514.png)

**Comment by Hiro-Nakamura** [comment]
So, are you saying this is happening when you Add a new field definition?  or when you try to assign a value to a current connected field?

**Comment by nh758** [comment]
The error message displays when adding the field definition. After reloading the field is shown in object builder, but not usable.
