### ISSUE TITLE
Widgets missing from menu

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#182]
**Describe the bug**
Certain widgets are not available on experimtal

**To Reproduce**
1. Click Add Widget

![image](https://user-images.githubusercontent.com/10155226/93859737-34ff9a00-fce8-11ea-91dd-b7cd6e432b63.png)
*Missing: Conditional Container, CSV Importer, Label, Layout*

**Expected behavior**
All Widgets are available 
![image](https://user-images.githubusercontent.com/10155226/93859833-5d879400-fce8-11ea-9db3-8b55718722e6.png)
(from Trial)

**Server**
Experimental

**Comment by Hiro-Nakamura** [comment]
My guess is this is actually related to the missing labels.  The icons are technically still there, but pushed off to the right?

**Comment by jamesduncan** [comment]
This is what I see when I try to run the reSetup.js

`    Label Import System ...
    Label Import ...
    *** 
    *** error selecting languages from test_docker.site_multilingual_language table:
    *** {    "message": "ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'10.0.31.4' (using password: YES)",    "stack": [        "Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'10.0.31.4' (using password: YES)",
        "    at Handshake.Sequence._packetToError (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)",
        "    at Handshake.ErrorPacket (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)",
        "    at Protocol._parsePacket (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/Protocol.js:291:23)",
        "    at Parser._parsePacket (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/Parser.js:433:10)",
        "    at Parser.write (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/Parser.js:43:10)",
        "    at Protocol.write (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/Protocol.js:38:16)",
        "    at Socket.<anonymous> (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/Connection.js:88:28)",
        "    at Socket.<anonymous> (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/Connection.js:526:10)",
        "    at emitOne (events.js:96:13)",
        "    at Socket.emit (events.js:188:7)",
        "    --------------------",
        "    at Protocol._enqueue (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/Protocol.js:144:48)",
        "    at Protocol.handshake (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/protocol/Protocol.js:51:23)",
        "    at Connection.connect (/usr/local/lib/node_modules/appdev/node_modules/mysql/lib/Connection.js:116:18)",
        "    at Generator.Resource.loadDBConn (/usr/local/lib/node_modules/appdev/lib/generators/labels.js:391:12)",
        "    at recurseProcess (/usr/local/lib/node_modules/appdev/lib/generators/class_generator.js:773:34)",
        "    at /usr/local/lib/node_modules/appdev/lib/generators/class_generator.js:784:21",
        "    at checkIt (/usr/local/lib/node_modules/appdev/lib/generators/labels.js:244:13)",
        "    at /usr/local/lib/node_modules/appdev/lib/generators/labels.js:248:17",
        "    at Generator.Resource.verifySetting (/usr/local/lib/node_modules/appdev/lib/generators/labels.js:209:9)",
        "    at checkIt (/usr/local/lib/node_modules/appdev/lib/generators/labels.js:247:18)"
    ],
    "code": "ER_ACCESS_DENIED_ERROR",
    "errno": 1045,
    "sqlMessage": "Access denied for user 'root'@'10.0.31.4' (using password: YES)",
    "sqlState": "28000",
    "fatal": true
}
    *** sql:
    *** select * from test_docker.site_multilingual_language
    *** 
    
`

**Comment by Hiro-Nakamura** [comment]
The labels have been properly updated now.  

FYI: for the setup functions, the cli label commands look for installed db connection info in the `/app/.adn` config file.

These settings were copied into the docker from my local environment and not updated with the running values of the current system.  I modified it to match the `/app/config/local.js` settings and now the label updates work on the `reSetup.js` script.
