### ISSUE TITLE
Scopes not limiting records as expected

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#184]
**Describe the bug**
Scopes with 'allow all' unchecked are not limiting records as expected. 

**To Reproduce**
**A. Single Object Scope**
1. Add a new scope
2. Uncheck Allow All
3. Add a Single Object
4. Log in with a user only assigned that scope

Result: The user cannot see records in any object
Expected: User can see records in specified object not others.

**B. Filtered Object Scope**
1. Add a filter to the object from the scope above
2. Log in as the user

Result: User sees filtered records in the object specified and all records in other objects
Expected: User sees filtered records in the object specified and no records in other objects

**Server**
Experimental, Trial

**Comment by wei9528** [comment]
@wongpratan VPS also has this issue, could you please add the changes on hat server? Thanks.

**Comment by wei9528** [comment]
I can still see a similar issue on VPS. 
Reproduce steps:
1. Set user A's QX. e.g CD.
2. Set 'Accountant' as A's role.
3. This is the scope for accountant role. 
![scope](https://user-images.githubusercontent.com/67583075/97385009-cd9ec080-190b-11eb-9659-4cfd9bdd0dd8.png) 
4. Log in with user A as an accountant role (the user only has acceptant role, no other roles).   
5. Notice that user A should only see batches submitted by users from QX CD, but the users can see all batches.
