### ISSUE TITLE
[Accounting App] Remove question marks and 'Close Month' button 

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#190]
When a fiscal month is not ready to close, click 'Close Month' button, below window will appear and contain some questions marks, which is not meaningful for users, and 'Close Month' may confuse and mislead the users. 
![CloseMonth](https://user-images.githubusercontent.com/67583075/94240161-780a7900-ff45-11ea-9898-361b0a0031c2.png)

**Comment by nh758** [comment]
This is caused by a problem with the conditional container as reported in #186

**Comment by wei9528** [comment]
It displays properly if the month's batches are all Completed.

**Comment by Achoobert** [comment]
OK if that's the case then it should display something else. I'll take a look

**Comment by wei9528** [comment]
Fixed, Close Month window looks good
![Screenshot 2020-09-28 at 10 10 03 AM](https://user-images.githubusercontent.com/67583075/94383493-cd779d80-0172-11eb-9072-56871c0b929e.png)
