### ISSUE TITLE
Issues on Experimental 

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#192]
Testing Environment: https://experimental.digiserve.org/

1. Connected fields (Account and RC Code) are missing in the Journal Entries page and CSV Importer. 
![csv](https://user-images.githubusercontent.com/67583075/94635979-77d3fa00-0306-11eb-85f6-feee9abdf49e.png)

2. Archived JE grid page is blank in the Completed Batch detail page after approved a submitted batch, all approved JEs go to unsubmitted batches. in the Object Builder, those approved JEs are in the  **Journal Entry** object instead of JE Archive object. JE Archive and Balances objects are still empty after batch is approved.
![CompletedBatch](https://user-images.githubusercontent.com/67583075/94636031-96d28c00-0306-11eb-8883-12dec2154c7a.png)

3. Failed to run GL Transactions report.

**Comment by Achoobert** [comment]
* this is only on the front end. the fields appear perfectly in the interface builder

**Comment by wei9528** [comment]
@wongpratan I can delete records in JE Archive object on Experimental, it is not allowed to delete JE Archive records on VPS.

**Comment by nh758** [comment]
> I can delete records in JE Archive object on Experimental, it is not allowed to delete JE Archive records on VPS.

This is expected. VPS has custom database permissions set up because it is a production accounting system.

**Comment by nh758** [comment]
1. I'm not seeing this. Maybe someone already fixed it.
2. The Balance Update process requires Account **Category** to be set. Not expected to work without.
3. I don't think GL transactions would work, as there no JE Archives yet.

Recommend setting Account Categories and testing again.
