### ISSUE TITLE
BUG Experimental: process manager crashed?

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#193]
To reproduce:  COMPLETE a Batch

I suspect this is either from:
"3991Net Income (Loss) Year to Date" being missing from my COA object
or
The process looking for a "Category" when I only had "Type" filled out
or
A bug from noarango

Note the lack of journal entries
![image](https://user-images.githubusercontent.com/8057443/94645110-3565e980-0315-11eb-8233-e0ba73913084.png)

but here, the accounts are connected to a LOT of journal entries
![image](https://user-images.githubusercontent.com/8057443/94645141-4b73aa00-0315-11eb-85a4-dcb662d20529.png)

**Comment by nh758** [comment]
I'm not clear what you mean by 'crashed'. Yes Account **Category** must be set and a 3991 account must be added. The process will not work without. Not a bug.

Also not clear what you mean about the JEs, there is a filter set which is why you only saw one. Let me know if I'm misunderstanding.
