### ISSUE TITLE
Allow builder to hide fields on CSV uploader

### ISSUE THREAD

**Issue by Achoobert** [appdevdesigns/app_builder#194]
![image](https://user-images.githubusercontent.com/8057443/94760305-52a9bf00-03cc-11eb-9175-e566df208693.png)
![image](https://user-images.githubusercontent.com/8057443/94760344-77059b80-03cc-11eb-8b2b-9987dda661e9.png)

**Comment by wongpratan** [comment]
https://github.com/appdevdesigns/app_builder/commit/92f19118febc33d8e7663e17c440a666fd9c0942

**Comment by wongpratan** [comment]
https://github.com/appdevdesigns/app_builder/commit/92f19118febc33d8e7663e17c440a666fd9c0942

This feature is added.
