### ISSUE TITLE
[Accounting App] Set Completed Batches page default to current month

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#199]
Completed Batches page displays all closed and active months' batches, and users need to display data only for current month in default, and they can use filter to look for previous month's data.
![CompletedBatches](https://user-images.githubusercontent.com/67583075/95937533-9360f980-0e0a-11eb-8b3b-0713e515644f.png)

**Comment by nh758** [comment]
There is currently no option to set a default filter on a grid. We can set a filter on the data collection used in the grid, but user would not be able to remove it.

**Comment by Achoobert** [comment]
> no option to set a default filter on a grid. 

Do we want to filter the data collection until this feature is added?

**Comment by wei9528** [comment]
> > no option to set a default filter on a grid.
> 
> Do we want to filter the data collection until this feature is added?

I don't think so, adding a filter on the data collection cannot solve this problem, and exclude some data which user is unable to filter out in the UI.

**Comment by nh758** [comment]
Opened appdevdesigns/planning#61
