### ISSUE TITLE
Generated clientside models have incorrect url.

### ISSUE THREAD

**Issue by suredoes** [appdevdesigns/app_builder#2]
the slash after opstools is backwards.

steal(
'opstools\AB_EventManager/models/base/AB_EventManager_events.js',
function() {

**Comment by appdevdesigns** [comment]
the appdev cli resource command  uses this code:

this.templateData.appName =
        this.pathProperSeparators( this.templateData.appName );

and that seems to switch the '/'  to '\'  on windows.  But it is being used in the steal url string and should not switch to '\'.

Is there another use for appName that requires the '\'  ?

**Comment by appdevdesigns** [comment]
This is actually an issue with the appdev-cli resource generator.
