### ISSUE TITLE
[Accounting App] Unsubmitted Batches page shows Submitted Batches when log in as Accountant 

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#200]
**To Reproduce**
1. Go to https://vps-internal.appdevdesigns.net/
2. Log in as an accountant user.
3. Created a batch and submitted it.
4. Log out.
5. Relog in. 
6. Notice that the batch submitted in #3 shows up in the Unsbumitted batch page. 
![unsubmitted](https://user-images.githubusercontent.com/67583075/95940833-ebe7c500-0e11-11eb-874b-a48599d4919e.png)

**Comment by Achoobert** [comment]
This is either because the [**Draft Batches**] data collection **isn't updated** when that batch is submitted, or the filter on the data collection is wrong. 

Hopefully it is just a missing filter!

**Comment by Achoobert** [comment]
The filter looks fine. 
![image](https://user-images.githubusercontent.com/8057443/95947427-c8744880-0e18-11eb-9571-d92b254b8a8d.png)


@wei9528  was BATCH-0000000195 submitted that same session, or does it still show after refresh?

**Comment by wei9528** [comment]
@Achoobert if I changed the batch user to Full Access, the submitted batch only displays in the Submitted Batches page, the Submitted Batch only shows up in the Unsubmitted Batches page when the batch users's role is **Accountant**.

**Comment by Achoobert** [comment]
> the Submitted Batch only shows up in the Unsubmitted Batches page when the **batch users's** role is....

What do you mean by "batch user?" 
The creator of the batch? 
So other users see the batch showing up in the UI depending on the creator's scope?

**Comment by wei9528** [comment]
Verified on VPS, submitted batches won't show up in the unsubmitted batches page. 
Closing..
