### ISSUE TITLE
Unable to Edit data in Object Table

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/app_builder#3]
Process:
Define a new Object
Add a column
Add row of data
Add data to that column
Define a different Object
add some columns
Go back to Object 1
Try to Edit the existing data - > Fails

Add another column
enter data into column

Switch to Object 2
Switch back to Object 1

Try to edit any of the columns -> Fails

**Comment by wongpratan** [comment]
I could not reproduce it.
If it still happens, then please reopen it.
