### ISSUE TITLE
Would like to have a Multi Select List

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/app_builder#4]
Currently we only have a Single Select List.

Would like an option to save multiple selections.

**Comment by hahn-kev** [comment]
I'll look into this, do we have a UI control in mind? I'm thinking we could just  store the data in a string column with just comma delimited values.

**Comment by hahn-kev** [comment]
It looks like webix has a multicombo control, do we have access to the pro version? http://docs.webix.com/desktop__multicombo.html

**Comment by appdevdesigns** [comment]
Hey, thanks for helping out.

We do not have access to the pro features of Webix.  Instead we have been making custom components for those features when we need them.

The data field that implements the select list is:  ``` assets/opstools/BuildApp/controllers/data_fields/list.js ```

This list would need to be extended with a ``` [] multiselect ``` checkbox in it's edit definition.  If not checked, it's current operation would be preserved.  If selected, then we would want to update it with a multiselect display.

Currently there is another data field that implements a multiselect feature: ``` connectObject.js ```

``` connectObject.js ``` currently uses [Selectivity.js](https://arendjr.github.io/selectivity/) to display it's selected values.  There is currently a utility for helping to display these values in ``` assets/opstools/BuildApp/controllers/utils/SelectivityHelper.js ```.

When needing to select new entries, there is a custom Webix control in ``` assets/opstools/BuildApp/controllers/webix_custom_components/ConnectedDataPopup.js ```.  This becomes the popup used to select multiple elements and save them.

The ``` ConnectedDataPopup.js ``` is very tailored to the model data it is representing. 

In this case, we would need a more generic ``` ABMultiselectPopup.js ``` that allows us to specify a data set, which ones are currently selected, and receive a new set of that data.

**Comment by hahn-kev** [comment]
I've been looking into this and I think I'm going to need to modify `dataFieldsManager.hasCustomEdit` to pass in the column itself so that I can access settings, because the field will have a custom edit if it's a  multiselect column, otherwise it won't, but currently there's no way from what I can tell to get the settings for the column in that method. Am I correct in this assessment?

**Comment by appdevdesigns** [comment]
OK, after talking this over with the original developer (@ wongpratan ), we've made the following change: a69f82b
(there should be a follow up commit that ensures the `fieldData` values get properly supplied)

Now the dataField can respond to ``` .hasCustomEdit() ``` directly.

After our discussions, it seems like the approach should be:

**if (`.multiselect`) is NOT checked:**
	`.getSettings()`: return normal 'richselect' webix definition
	`.hasCustomEdit()`: return false
	`.customEdit()`: do nothing, return true;
	`.customDisplay()`: do nothing, return false;


**if (`.multiselect`) is checked:**
	`.getSettings()`: return 'template' type of webix definition
	`.hasCustomEdit()` : return true;
	`.customEdit()`: find embedded template, and initialize it with your editor. return true;
	`.customDisplay()`: find embedded template, and initialize it with your values. return true;

**Comment by appdevdesigns** [comment]
@ wongpratan

**Comment by hahn-kev** [comment]
Great, that's what I was thinking of doing. I don't see any changes to the call sites of `hasCustomEdit` don't those need to be changed too?

**Comment by Hiro-Nakamura** [comment]
Yeah, I’ve told the other developer to make the changes.  He hasn’t pushed them up yet.

**Comment by appdevdesigns** [comment]
should be there now:  6695c0c
